import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Archilawn</title>
        {/* Bootstrap */}
        <link rel="stylesheet" href="asset/css/bootstrap.min.css" />
        <link rel="stylesheet" href="asset/css/custom.css" />
      </head>

      <body className={inter.className}>
        {/* slider area start */}
        <div className="slider_area">
          <nav className="navbar navbar-expand-lg">
            <div className="container-fluid">
              <a className="navbar-brand" href="#">
                <img src="./asset/img/logo.png" alt="" />
              </a>
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon" />
              </button>
              <div className="row">
                <col-md-6> </col-md-6>
              </div>
              <div
                className="collapse navbar-collapse justify-content-center"
                id="navbarSupportedContent"
              >
                <ul className="navbar-nav mb-2 mb-lg-0">
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      Packages
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      How it works
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      Portfolio
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      Our Designers
                    </a>
                  </li>
                </ul>
              </div>
              <div className="d-flex text-end">
                <a className="nav-link login_btn mt-2" href="#">
                  Login
                </a>
                <button className="btn call_us_btn ms-3">
                  <span>
                    <i
                      className="fa-solid fa-phone fa-sm"
                      style={{ color: "#ffffff", marginRight: 10 }}
                    />
                  </span>
                  call us
                </button>
                <button className="btn ms-3 sms_btn">
                  <span>
                    <i
                      className="fa-solid fa-envelope"
                      style={{ color: "#000000" }}
                    />
                  </span>
                </button>
              </div>
            </div>
          </nav>
          {/* slider content */}
          <div className="slider_content">
            <h2>
              Visualize your project with <span>Realistic</span> 3D
              <span>Rendering</span>
            </h2>
            <p>
              Partner with a professional Architect &amp; landscape designer for
              customized plans and 3d visualization. All Online.
            </p>
          </div>
          <div className="social_medial">
            <a href="#">
              <i
                className="fa-brands fa-facebook-f fa-sm"
                style={{ color: "#ffffff" }}
              />
            </a>
            <a href="#">
              <i
                className="fa-brands fa-linkedin-in"
                style={{ color: "#ffffff" }}
              />
            </a>
            <a href="#">
              <i
                className="fa-brands fa-twitter"
                style={{ color: "#ffffff" }}
              />
            </a>
            <a href="#">
              <i
                className="fa-brands fa-instagram"
                style={{ color: "#ffffff" }}
              />
            </a>
          </div>
        </div>
        {children}

        <section className="footer_section">
          <div className="row m-0 footer_body">
            <div className="col-md-6 p-5 footer_left">
              <img
                src="./asset/img/logo.png"
                className="img-fluid mb-3"
                alt="img"
              />
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
                ipsum lorem, tempor ut ex aliquam, fringilla lacinia quam. Sed
                mattis ante at massa aliquet consectetur.
              </p>
              <div className="footer_icon mt-5">
                <a href="#">
                  <i
                    className="fa-brands fa-facebook-f fa-sm"
                    style={{ color: "#ffffff" }}
                  />
                </a>
                <a href="#">
                  <i
                    className="fa-brands fa-linkedin-in"
                    style={{ color: "#ffffff" }}
                  />
                </a>
                <a href="#">
                  <i
                    className="fa-brands fa-twitter"
                    style={{ color: "#ffffff" }}
                  />
                </a>
                <a href="#">
                  <i
                    className="fa-brands fa-instagram"
                    style={{ color: "#ffffff" }}
                  />
                </a>
              </div>
            </div>
            <div className="col-md-6 footer_right">
              <div className="row">
                <div className="col-6 footer_chi_left">
                  <h5>EXPLORE</h5>
                  <ul>
                    <li>Home</li>
                    <li>About</li>
                    <li>Booking</li>
                    <li>Gallery</li>
                    <li>Contact</li>
                  </ul>
                </div>
                <div className="col-6 footer_chi_right">
                  <h5>GET IN TOUCH</h5>
                  <ul>
                    <li>
                      <span>
                        <i
                          className="fa-solid fa-phone fa-sm"
                          style={{ color: "#ffffff", marginRight: 10 }}
                        />
                      </span>
                      +8801714613653
                    </li>
                    <li>
                      <span>
                        <i
                          className="fa-solid fa-phone fa-sm"
                          style={{ color: "#ffffff", marginRight: 10 }}
                        />
                      </span>
                      +8801714613653
                    </li>
                    <li>
                      <span>
                        <i
                          className="fa-solid fa-phone fa-sm"
                          style={{ color: "#ffffff", marginRight: 10 }}
                        />
                      </span>
                      +8801714613653
                    </li>
                  </ul>
                  <h5>ADDRESS</h5>
                  <p>20 The Esplanade Surfers Paradise, Australia</p>
                </div>
              </div>
            </div>
          </div>
          <div className="row m-0 copyright_body">
            <div className="col-md-6 copyright d-flex align-items-center">
              <p className="m-0 p-3">
                Copyright © 2024 All Rights Reserved by archilawn
              </p>
            </div>
            <div className="col-md-6 copyright text-end">
              <p className="m-0 p-3">Terms | Privacy | Cookies | Sitemap</p>
            </div>
          </div>
        </section>

        {/* JS */}
        <script src="asset/js/bootstrap.bundle.min.js"></script>
        <script
          src="https://kit.fontawesome.com/14c3ef5dcc.js"
          crossorigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
